CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  nom_ar VARCHAR(255),
  nom_en VARCHAR(255),
  nom_fr VARCHAR(255),
  prenom_ar VARCHAR(255),
  prenom_en VARCHAR(255),
  prenom_fr VARCHAR(255),
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  photo TEXT,
  is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
