// Auto-generated from the uploaded Trade in Critical Minerals data
export const tradeCriticalMineralsData = [
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2010,
    value_usd: 113615721.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2016,
    value_usd: 87553542.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2010,
    value_usd: 61132213.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2014,
    value_usd: 56728294.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2015,
    value_usd: 54010871.32,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2014,
    value_usd: 42420161.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2015,
    value_usd: 41163510.47,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2019,
    value_usd: 39762201.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2011,
    value_usd: 37902998.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2017,
    value_usd: 34042865.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2020,
    value_usd: 29280530.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2016,
    value_usd: 29242876.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2012,
    value_usd: 27338341.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2017,
    value_usd: 27271198.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2021,
    value_usd: 24084027.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2019,
    value_usd: 23836901.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2018,
    value_usd: 22610973.21,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2013,
    value_usd: 18730715.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2018,
    value_usd: 17511598.32,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2011,
    value_usd: 16463300.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2021,
    value_usd: 16286130.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2020,
    value_usd: 16047264.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2022,
    value_usd: 14813003.77,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2022,
    value_usd: 12705400.38,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2023,
    value_usd: 12401542.31,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710812",
    hs_description: "Metals; gold, non-monetary, unwrought (but not powder)",
    year: 2023,
    value_usd: 6742923.469,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2017,
    value_usd: 4322674.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2014,
    value_usd: 3042374.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2019,
    value_usd: 2016855.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2015,
    value_usd: 1821661.974,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2016,
    value_usd: 1697206.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2018,
    value_usd: 1116923.511,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "261690",
    hs_description: "Precious metal ores and concentrates; (excluding silver)",
    year: 2012,
    value_usd: 478405.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2022,
    value_usd: 473320.751,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2021,
    value_usd: 387680.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2011,
    value_usd: 225753.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2020,
    value_usd: 154223.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2012,
    value_usd: 109860.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2018,
    value_usd: 86998.97,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2015,
    value_usd: 81927.54,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2023,
    value_usd: 71301.12305,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2014,
    value_usd: 53382.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2020,
    value_usd: 35810.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2016,
    value_usd: 34717.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2023,
    value_usd: 30425.24219,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710813",
    hs_description: "Metals; gold, semi-manufactured",
    year: 2012,
    value_usd: 28105.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2018,
    value_usd: 26378.256,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2019,
    value_usd: 20879.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2011,
    value_usd: 11287.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2016,
    value_usd: 10385.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800200",
    hs_description: "Tin; waste and scrap",
    year: 2013,
    value_usd: 9080.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2014,
    value_usd: 6090.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800120",
    hs_description: "Tin; unwrought, alloys",
    year: 2020,
    value_usd: 5669.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2015,
    value_usd: 3672.003,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2022,
    value_usd: 3347.223,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2016,
    value_usd: 3146.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2022,
    value_usd: 2922.94,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2023,
    value_usd: 2483.924744,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2017,
    value_usd: 2225.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2013,
    value_usd: 1467.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Gold",
    hs_code: "710900",
    hs_description: "Base metals or silver; clad with gold, not further worked than semi-manufactured",
    year: 2023,
    value_usd: 1441.328979,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2021,
    value_usd: 1284.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2015,
    value_usd: 1116.537,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2019,
    value_usd: 953.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2010,
    value_usd: 861.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2017,
    value_usd: 599.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800120",
    hs_description: "Tin; unwrought, alloys",
    year: 2018,
    value_usd: 587.299,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800500",
    hs_description: "Tin; foil (whether or not printed or backed with paper, paperboard, plastics or similar backing materials), of a thickness (excluding any backing) not exceeding 0.2mm, tin powders and flakes",
    year: 2013,
    value_usd: 539.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2018,
    value_usd: 501.486,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2019,
    value_usd: 385.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2020,
    value_usd: 336.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800700",
    hs_description: "Tin; articles n.e.c. in chapter 80",
    year: 2014,
    value_usd: 285.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800600",
    hs_description: "Tin; tubes, pipes and tube or pipe fittings (eg couplings, elbows, sleeves)",
    year: 2012,
    value_usd: 232.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800120",
    hs_description: "Tin; unwrought, alloys",
    year: 2021,
    value_usd: 215.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800300",
    hs_description: "Tin; bars, rods, profiles and wire",
    year: 2012,
    value_usd: 34.0,
  },
  {
    reporter: "Morocco",
    partner: "World",
    flow: "Export",
    aggregate_product: "Tin",
    hs_code: "800110",
    hs_description: "Tin; unwrought, not alloyed",
    year: 2016,
    value_usd: 5.0,
  },
];

export const tradeCriticalMineralsMeta = {
  title: "Trade in Critical Minerals",
  currency: "USD",
  total_value_usd: 900087110.357963,
  reporter: "Morocco",
  partner: "World",
  flow: "Export",
};

export const tradeCriticalMineralsByProduct = {
  gold: { label: "Gold", total_value_usd: 898224746.062979 },
  tin: { label: "Tin", total_value_usd: 1862364.294984 },
};

export const tradeCriticalMineralsByYear = {
  2010: 174748795.0,
  2011: 54603338.0,
  2012: 27954977.0,
  2013: 18741801.0,
  2014: 102250586.0,
  2015: 97082759.844,
  2016: 118541877.0,
  2017: 65639561.0,
  2018: 41353961.052,
  2019: 65638174.0,
  2020: 45523832.0,
  2021: 40759336.0,
  2022: 27997995.064,
  2023: 19250117.397963,
};

export default tradeCriticalMineralsData;